Repository wikicurricula-uy/wikicurricula-boilerplate, pull requests merged in 2023-10, with the labels that each got.

#21 Fixes #15 - Improve design of Credits section
  visualization/assets/script/dv1.js
  visualization/index.html
Labels: documentation

#37 Updated credit/footer section
  visualization/index.html
Labels: documentation

#57 Conflicts resolved: Documentation, Translation, Fetching list of articles from wikidataApi
  Execute-Wikidata-Query.png
  README.md
  Wikidata-Query.png
  data-gathering/Execute-Wikidata-Query.png
  data-gathering/Python-Wikidata-Query.png
  data-gathering/README.md
  data-gathering/Wikidata-Query.png
  data-gathering/ghana-curriculum.csv
  data-gathering/main.py
  visualization/assets/style/style.css
  visualization/autori/index.html
  visualization/avvisi/index.html
  visualization/index.html
  wikicurricula-visualization.png
Labels: documentation, enhancement

#54 Fixed and enabled the feature that counts the templates (avisi) added to an article.
  .vscode/settings.json
  README.md
  data-gathering/__pycache__/bot.cpython-311.pyc
  data-gathering/bot.py
  data-gathering/query.csv
  data-gathering/query.py
  data-gathering/resultati.txt
  data-gathering/results.txt
  data-gathering/translate.py
  data-gathering/voci_2023.tsv
  visualization/assets/data/voci_2023
  visualization/assets/data/voci_2023.tsv
  visualization/assets/script/dv1.js
  visualization/assets/script/utilities.js
  visualization/authors/index.html
  visualization/ghana.html
  visualization/index.html
Labels: enhancement

#31 Fixes #28 - Add tick marks to the x axis in the main visualization page
  visualization/assets/script/dv1.js
Labels: enhancement

#44 Bug fixed #27 - Ordering by refrence changes according to subject
  visualization/assets/script/dv1.js
Labels: enhancement

#24 Added a CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation

#60 Implement and deploy wikicurricula for ghana at toolforge
  README.md
  data-gathering/README.md
  data-gathering/bot.py
  data-gathering/ghana_article_file.csv
  data-gathering/ghana_results.txt
  data-gathering/ghana_subject_file.csv
  data-gathering/it-config.py
  data-gathering/language_template_config.json
  data-gathering/query.py
  data-gathering/results.txt
  data-gathering/subjects.csv
  data-gathering/super_bot.py
  data-gathering/translate.py
  data-gathering/uruguay_article_file.csv
  data-gathering/uruguay_results.txt
  data-gathering/uruguay_subject_file.csv
  data-gathering/voci_2023.tsv
  data-gathering/wikipedia_config.json
  visualization/assets/data/ghana_voci_2023.tsv
  visualization/assets/data/uruguay_voci_2023.tsv
  visualization/assets/data/voci_2023.tsv
  visualization/assets/script/dv1.js
  visualization/assets/script/utilities.js
  visualization/ghana.html
  visualization/index.html
Labels: enhancement

#53 Implement Dark Mode
  .vscode/settings.json
  visualization/assets/script/dark-mode.js
  visualization/assets/style/dark-mode.css
  visualization/ghana.html
  visualization/index.html
Labels: enhancement

#6 Translated Version of the boilerplate's interface to English
  visualization/assets/img/dv1_legend_b.svg
  visualization/index.html
Labels: enhancement
